name: 'Make Pear Apps'
description: 'Action for making Pear apps'
inputs:
  build_certificate_base64:
    description: 'Base64 Apple distribution certificate'
    required: false
    default: ''
  p12_password:
    description: 'Password for Apple certificate'
    required: false
    default: ''
  build_provision_profile_base64:
    description: 'Base64 Apple provisioning profile'
    required: false
    default: ''
  keychain_password:
    description: 'Temporary keychain password'
    required: false
    default: ''
  apikey_base64:
    description: 'Base64 Apple API key'
    required: false
    default: ''
  apikey_id:
    description: 'Apple API Key ID'
    required: false
    default: ''
  apikey_issuer:
    description: 'Apple API Key issuer ID'
    required: false
    default: ''
  macos_codesign_identity:
    description: 'macOS codesign identity'
    required: false
    default: ''
  win_subject:
    description: 'Windows code signing certificate subject'
    required: false
    default: ''
  win_thumbprint:
    description: 'Thumbprint of the Windows code signing certificate'
    required: false
    default: ''
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
    - name: 'Install dependencies (Linux/macOS)'
      if: ${{ runner.os != 'Windows' }}
      run: |
        npm install
      shell: bash
    - name: 'Install dependencies (Windows)'
      if: ${{ runner.os == 'Windows' }}
      run: |
        npm install
      shell: pwsh
    - name: 'Install the Apple certificate and provisioning profile'
      if: ${{ runner.os == 'macOS' }}
      run: |
        # create variables
        CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
        PP_PATH=$RUNNER_TEMP/build_pp.provisionprofile
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
        APIKEY_PATH=$RUNNER_TEMP/AuthKey.p8

        # import certificate and provisioning profile from secrets
        echo -n "${{ inputs.build_certificate_base64 }}" | base64 --decode -o $CERTIFICATE_PATH
        echo -n "${{ inputs.build_provision_profile_base64 }}" | base64 --decode -o $PP_PATH
        echo -n "${{ inputs.apikey_base64 }}" | base64 --decode -o $APIKEY_PATH

        # create temporary keychain
        security create-keychain -p "${{ inputs.keychain_password }}" $KEYCHAIN_PATH
        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
        security unlock-keychain -p "${{ inputs.keychain_password }}" $KEYCHAIN_PATH

        # import certificate to keychain
        security import $CERTIFICATE_PATH -P "${{ inputs.p12_password }}" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security set-key-partition-list -S apple-tool:,apple: -k "${{ inputs.keychain_password }}" $KEYCHAIN_PATH
        security list-keychain -d user -s $KEYCHAIN_PATH

        # add notarytool credentials
        xcrun notarytool store-credentials 'notary' --key "$APIKEY_PATH" --key-id "${{ inputs.apikey_id }}" --issuer "${{ inputs.apikey_issuer }}"

        # apply provisioning profile
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
      shell: bash
    - name: 'Build application (Linux)'
      if: ${{ runner.os == 'Linux' }}
      run: |
        npm run make
      shell: bash
    - name: 'Build application (macOS)'
      if: ${{ runner.os == 'macOS' }}
      env:
        MAC_CODESIGN_IDENTITY: "${{ inputs.macos_codesign_identity }}"
      run: |
        npm run make
      shell: bash
    - name: 'Build application (Windows)'
      if: ${{ runner.os == 'Windows' }}
      env:
        WIN_SUBJECT: "${{ inputs.win_subject }}"
        WIN_THUMBPRINT: "${{ inputs.win_thumbprint }}"
      run: |
        npm run make
      shell: pwsh
    - name: 'Install @actions/artifact module (Linux/macOS)'
      if: ${{ runner.os != 'Windows' }}
      run: |
        npm install @actions/artifact@2.3.2 --global
        echo "NODE_PATH=$(npm root --quiet -g)" >> $GITHUB_ENV
    - name: 'Install @actions/artifact module (Windows)'
      if: ${{ runner.os == 'Windows' }}
      run: |
        npm install @actions/artifact@2.3.2 --global
        $npmRoot = npm root --quiet -g
        Add-Content -Path $env:GITHUB_ENV -Value "NODE_PATH=$npmRoot"
      shell: pwsh
    - name: 'Extract Actions runtime variables'
      uses: actions/github-script@v7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        script: |
          core.exportVariable('ACTIONS_RESULTS_URL', process.env['ACTIONS_RESULTS_URL'])
          core.exportVariable('ACTIONS_RUNTIME_URL', process.env['ACTIONS_RUNTIME_URL'])
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env['ACTIONS_RUNTIME_TOKEN'])
    - name: 'Upload folders as artifacts'
      env:
        NODE_PATH: "${{ env.NODE_PATH }}"
      run: |
        const fs = require('fs');
        const path = require('path');
        const { DefaultArtifactClient } = require('@actions/artifact');

        const artifact = new DefaultArtifactClient()

        function listFilesRecursive(dir) {
          let results = []
          const list = fs.readdirSync(dir)
          list.forEach(function(file) {
            const filePath = path.join(dir, file)
            const stat = fs.statSync(filePath)
            if (stat && stat.isDirectory()) {
              results = results.concat(listFilesRecursive(filePath))
            } else if (stat && stat.isFile()) {
              results.push(filePath)
            }
          })
          return results
        }

        const files = listFilesRecursive('out/make')
        files.forEach(file => {
          const artifactName = path.basename(file)
          console.log(`Uploading artifact: ${artifactName} from ${file}`)
          artifact.uploadArtifact(artifactName, [file], './out/make')
        })
      shell: node {0}
branding:
  icon: package
  color: green
